In [1]:
#importing pandas library as 'pd'
import pandas as pd

In [2]:
#Loading the file into pandas dataframe
dataset=pd.read_csv(r'C:\\Users\\Sowmya Sri\\OneDrive\\01.Data Cleaning and Preprocessing.csv')

In [3]:
#Concise summary of the dataframe
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      324 non-null    object
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF      323 non-null    float64
 18  BlackFlow-2      322 non-null    float64
 19  WeakWashF        323 non-null    float64
 20  SteamHeatF-3     322 non-null    float64
 21  T-Top-Chips-4    323 non-null    float64
 22  SulphidityL-4    173 non-null    float64
dtypes: float64(22), object(1)
memory usage: 58.3+ KB

In [4]:
#All the column names of the dataframe
dataset.columns

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 '],
      dtype='object')

In [5]:
#The total number of rows in the dataframe
dataset.index

RangeIndex(start=0, stop=324, step=1)

In [6]:
#Total elements of the dataframe
dataset.size

7452

In [7]:
#A quick look or a sample
dataset.head(10)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
6,1-09:00,13.49,13.700,98.186,1243.688,116.275,346.208,326.982,1.434,696.766,...,72.989,322.982,296.080,182.018,784.281,929.527,201.272,58.118,248.741,NaN
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
8,31-07:00,22.50,14.233,97.249,1346.900,330.325,352.687,328.894,1.480,591.827,...,68.791,331.485,303.488,174.804,889.516,1317.912,226.319,52.546,250.414,NaN
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21

In [8]:
#The latest data from the dataframe
dataset.tail(10)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
314,8-13:00,16.70,NaN,NaN,NaN,0.000,373.867,324.184,1.596,533.538,...,59.310,328.206,304.038,150.399,705.880,1145.549,481.277,50.671,250.683,29.252
315,8-14:00,16.05,13.114,NaN,NaN,0.000,NaN,NaN,1.648,500.376,...,55.180,329.185,303.149,141.763,865.254,NaN,491.514,47.943,251.696,NaN
316,8-15:00,17.75,11.283,NaN,NaN,41.607,362.545,331.240,1.658,467.265,...,50.663,NaN,NaN,128.396,836.060,1195.731,418.192,NaN,251.889,29.580
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
318,4-17:00,18.20,16.283,83.508,1288.104,234.284,359.412,328.670,1.534,692.687,...,74.528,321.224,298.231,173.827,854.573,1174.267,62.077,50.653,252.474,NaN
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700
321,9-20:00,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN

In [9]:
#Null values in each column
dataset.isna().sum()

Observation          0
Y-Kappa              0
ChipRate             5
BF-CMratio          17
BlowFlow            16
ChipLevel4           1
T-upperExt-2         2
T-lowerExt-2         2
UCZAA               25
WhiteFlow-4          1
AAWhiteSt-4        151
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        2
Upper-HeatT-3        2
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          2
WeakWashF            1
SteamHeatF-3         2
T-Top-Chips-4        1
SulphidityL-4      151
dtype: int64

In [10]:
#Null values' presence in each column per row
dataset.isnull()

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
320,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
321,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
322,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
323,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [11]:
#Dropping the rows with null values
new_dataset = dataset.dropna()
new_dataset

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.340
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,62.179,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130

In [12]:
print("The dataset length before removing null values is: ", len(dataset))
print("The dataset length after removing null values is: ", len(new_dataset))
print("The number of rows removed is: ", len(dataset) - len(new_dataset))

The dataset length before removing null values is:  324
The dataset length after removing null values is:  141
The number of rows removed is:  183

In [13]:
#Filling the null values with "No data collected"
data = dataset.fillna("No data collected")
data

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.52,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,No data collected
1,31-01:00,27.60,16.81,79.022,1328.36,341.327,351.05,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.26,1.6,549.611,...,61.304,329.14,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,No data collected
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.64,332.709,No data collected,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,10-16:00,23.75,12.667,93.45,1178.252,276.955,347.286,310.97,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.7
321,9-20:00,23.01,12.55,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,No data collected
322,9-21:00,24.32,13.083,88.91,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.0,43.725,253.176,31.13
323,9-22:00,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.84,253.216,No data collected

In [14]:
dataset.drop('Observation', axis=1)

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,NaN,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,NaN,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,6.110,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,6.068,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.86
320,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,6.190,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.70
321,23.01,12.550,90.842,1188.517,289.826,373.633,314.591,1.457,549.306,NaN,...,66.446,330.226,304.686,160.841,887.125,1319.226,0.638,45.549,252.438,NaN
322,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,6.128,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.13
323,25.75,13.417,85.451,1186.342,248.312,356.289,310.482,1.474,497.375,NaN,...,58.247,328.092,304.093,144.218,828.328,1320.848,1.276,43.840,253.216,NaN

In [15]:
new_dataset.describe()

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,...,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000,141.000000
mean,20.780567,14.407277,86.842078,1241.878766,267.190312,356.841801,324.062270,1.497695,593.977879,6.144872,...,67.072582,325.484702,300.425092,162.551035,864.687546,1169.562624,271.164106,49.509894,251.274057,30.456674
std,3.104667,1.501403,7.447316,72.414829,80.965627,9.924441,7.850917,0.103568,67.695750,0.080408,...,5.508386,4.586752,4.506755,14.200656,124.824316,151.937463,159.624109,4.648990,1.266735,0.684127
min,12.170000,10.833000,68.645000,954.092000,0.000000,340.222000,287.705000,1.182000,405.111000,5.890000,...,51.192000,318.821000,293.312000,113.922000,493.856000,838.948000,0.000000,35.510000,248.390000,29.020000
25%,18.500000,13.420000,81.087000,1194.181000,219.669000,350.155000,321.295000,1.437000,540.558000,6.093000,...,62.809000,321.448000,296.667000,153.147000,771.158000,1026.333000,149.973000,46.603000,250.312000,30.130000
50%,20.750000,14.375000,86.950000,1276.082000,276.955000,357.367000,325.690000,1.500000,593.811000,6.140000,...,67.678000,323.430000,299.020000,163.258000,859.558000,1144.876000,282.044000,49.987000,251.406000,30.390000
75%,23.300000,15.542000,92.142000,1290.006000,332.497000,362.372000,329.403000,1.556000,642.588000,6.199000,...,71.649000,329.851000,304.135000,173.204000,965.018000,1318.725000,392.864000,52.807000,252.423000,30.860000
max,27.600000,16.817000,114.570000,1334.892000,419.014000,399.135000,333.706000,1.747000,731.394000,6.340000,...,76.147000,333.596000,310.487000,187.665000,1132.181000,1392.868000,598.171000,63.332000,254.122000,32.840000

In [16]:
new_dataset.sum()

Observation        31-01:0031-03:001-08:0031-06:0031-08:0031-10:0...
Y-Kappa                                                      2930.06
ChipRate                                                    2031.426
BF-CMratio                                                 12244.733
BlowFlow                                                  175104.906
ChipLevel4                                                 37673.834
T-upperExt-2                                               50314.694
T-lowerExt-2                                                45692.78
UCZAA                                                        211.175
WhiteFlow-4                                                83750.881
AAWhiteSt-4                                                  866.427
AA-Wood-4                                                   2515.484
ChipMoisture-4                                              6590.415
SteamFlow-4                                                 9457.234
Lower-HeatT-3                                              45893.343
Upper-HeatT-3                                              42359.938
ChipMass-4                                                 22919.696
WeakLiquorF                                               121920.944
BlackFlow-2                                                164908.33
WeakWashF                                                  38234.139
SteamHeatF-3                                                6980.895
T-Top-Chips-4                                              35429.642
SulphidityL-4                                               4294.391
dtype: object

In [17]:
data1  = new_dataset.filter(items=['Y-Kappa', 'UCZAA']) 
data1

     Y-Kappa  UCZAA
1      27.60  1.549
3      23.60  1.604
5      14.23  1.436
7      22.65  1.468
9      24.70  1.515
..       ...    ...
312    24.40  1.429
317    17.80  1.488
319    23.75  1.523
320    19.80  1.451
322    24.32  1.523

[141 rows x 2 columns]

In [18]:
filtered_data = new_dataset.loc[(new_dataset['Y-Kappa'] > 23) & (new_dataset['UCZAA'] > 1.7) | (new_dataset['BlowFlow'] < 1000) & (new_dataset['Y-Kappa'] < 22)]
filtered_data

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
279,11-14:00,21.27,11.383,84.165,981.920,342.858,352.315,322.292,1.553,592.539,...,73.134,333.596,310.487,171.004,940.938,1375.202,189.529,52.600,251.797,30.4
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.080,1.604,471.537,...,57.260,330.293,304.958,136.358,1067.280,1346.973,237.346,40.713,252.545,30.4

In [19]:
A= [998.153, 1008.98,]
data2=new_dataset[new_dataset['BlowFlow'].isin(A)]
data2

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
283,11-18:00,20.37,10.967,99.982,998.153,302.251,344.295,305.08,1.604,471.537,...,57.26,330.293,304.958,136.358,1067.28,1346.973,237.346,40.713,252.545,30.4

In [20]:
new_dataset.pivot_table(index='UCZAA', values='Y-Kappa')

       Y-Kappa
UCZAA
1.182    20.55
1.230    22.80
1.253    18.40
1.258    14.53
1.265    25.56
...        ...
1.678    24.16
1.689    18.50
1.691    23.12
1.710    17.81
1.747    21.40

[101 rows x 1 columns]

In [21]:
#Long format of the dataset
new_dataset.melt(id_vars='UCZAA', var_name='Company/Component', value_vars=('Y-Kappa', 'BlowFlow'))

     UCZAA Company/Component     value
0    1.549           Y-Kappa    27.600
1    1.604           Y-Kappa    23.600
2    1.436           Y-Kappa    14.230
3    1.468           Y-Kappa    22.650
4    1.515           Y-Kappa    24.700
..     ...               ...       ...
277  1.429          BlowFlow  1330.104
278  1.488          BlowFlow  1276.082
279  1.523          BlowFlow  1178.252
280  1.451          BlowFlow  1184.119
281  1.523          BlowFlow  1192.879

[282 rows x 3 columns]

In [22]:
#Renaming observation column
new_dataset.rename(columns={'Observation':'Obs'})

,Obs,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.340
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,62.179,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130

In [23]:
new_dataset = new_dataset.drop('Observation', axis=1)

In [24]:
new_dataset = new_dataset.drop_duplicates()

# Convert dataset columns to numeric data types

new_dataset = new_dataset.apply(pd.to_numeric, errors='coerce')

q1 = new_dataset.quantile(0.25)
q3 = new_dataset.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

# Outliers Data
outliers = new_dataset[(new_dataset < lower_bound) | (new_dataset > upper_bound)]

# Data with no outliers
no_outliers = new_dataset[(new_dataset >lower_bound) & (new_dataset <upper_bound)]


no_outliers

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
5,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,6.020,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
7,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,6.143,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
9,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,6.199,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,19.90,11.333,87.405,NaN,369.383,343.515,NaN,1.592,452.718,6.296,...,55.963,330.842,308.789,128.701,783.417,1293.108,390.049,41.596,252.428,30.73
292,22.00,11.858,93.199,1171.206,366.787,345.261,310.115,1.513,428.202,6.340,...,52.494,330.589,309.152,NaN,816.020,1294.891,391.607,42.080,253.206,30.24
294,19.00,12.425,92.905,1272.030,316.226,345.811,NaN,1.633,469.045,6.330,...,60.307,329.997,308.072,137.719,865.661,1292.216,391.645,44.330,253.323,30.31
296,20.50,13.358,97.662,1304.597,377.678,347.672,313.147,1.546,496.460,6.340,...,60.119,332.615,308.575,141.076,997.904,1334.703,389.497,46.206,252.423,30.43
298,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,6.340,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29

In [25]:
no_outliers.dropna()

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
5,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,6.020,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
7,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,6.143,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
9,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,6.199,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,21.25,14.192,91.907,1286.693,346.418,349.544,318.284,1.598,551.442,6.180,...,68.053,332.175,308.950,158.412,1038.187,1366.592,278.115,50.512,252.504,30.47
274,23.17,15.542,82.392,1280.501,334.242,348.771,316.870,1.596,558.715,6.220,...,68.318,331.510,309.023,156.631,859.558,1367.960,300.409,49.837,252.626,30.48
276,22.70,15.517,83.008,1288.010,306.886,350.155,322.485,1.590,568.752,6.170,...,67.678,331.854,309.346,160.061,910.013,1381.389,441.934,51.466,252.216,29.59
296,20.50,13.358,97.662,1304.597,377.678,347.672,313.147,1.546,496.460,6.340,...,60.119,332.615,308.575,141.076,997.904,1334.703,389.497,46.206,252.423,30.43
298,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,6.340,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29

In [26]:
#backfilling and forward filling the null values
no_outliers=no_outliers.bfill()
no_outliers=no_outliers.ffill()
no_outliers

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
5,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,6.020,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
7,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,6.143,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
9,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,6.199,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,19.90,11.333,87.405,1171.206,369.383,343.515,310.115,1.592,452.718,6.296,...,55.963,330.842,308.789,128.701,783.417,1293.108,390.049,41.596,252.428,30.73
292,22.00,11.858,93.199,1171.206,366.787,345.261,310.115,1.513,428.202,6.340,...,52.494,330.589,309.152,137.719,816.020,1294.891,391.607,42.080,253.206,30.24
294,19.00,12.425,92.905,1272.030,316.226,345.811,313.147,1.633,469.045,6.330,...,60.307,329.997,308.072,137.719,865.661,1292.216,391.645,44.330,253.323,30.31
296,20.50,13.358,97.662,1304.597,377.678,347.672,313.147,1.546,496.460,6.340,...,60.119,332.615,308.575,141.076,997.904,1334.703,389.497,46.206,252.423,30.43
298,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,6.340,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29

In [27]:
#Checking out if there are any null values
no_outliers.isnull().sum().sum()

0

In [28]:
#Statistics of a non-outliers dataset
no_outliers.describe()

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,...,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000
mean,20.665725,14.395328,86.630237,1247.697160,268.201771,356.297397,324.671863,1.500328,595.079710,6.147214,...,67.216702,325.265771,300.264160,162.736344,865.121061,1163.291947,273.059489,49.439611,251.266290,30.478275
std,3.021990,1.496178,7.148158,53.418633,78.805733,8.078226,6.332007,0.102147,68.208005,0.079816,...,5.457516,4.588467,4.578489,13.210437,126.237074,150.955336,158.311244,4.396194,1.276348,0.624997
min,12.170000,10.833000,68.645000,1084.886000,61.783000,340.222000,310.115000,1.253000,405.111000,5.940000,...,52.494000,318.821000,293.312000,128.701000,493.856000,838.948000,0.000000,38.642000,248.390000,29.020000
25%,18.490000,13.481000,81.164500,1198.625500,222.607500,350.338000,321.453000,1.438000,542.125000,6.096000,...,63.780500,321.282500,296.566500,153.032500,769.505500,1017.102500,151.810000,46.520000,250.307000,30.155000
50%,20.700000,14.417000,86.950000,1272.030000,275.798000,357.520000,325.690000,1.501000,596.506000,6.140000,...,68.023000,322.913000,298.517000,163.067000,860.372000,1141.946000,284.877000,49.987000,251.406000,30.400000
75%,23.185000,15.529500,92.024500,1289.225000,333.369500,362.392500,329.433500,1.566000,652.506500,6.200000,...,71.791500,329.821000,304.089500,173.134000,967.372000,1313.741500,396.471500,52.581000,252.423000,30.885000
max,27.600000,16.817000,108.104000,1334.892000,419.014000,375.047000,333.706000,1.747000,731.394000,6.340000,...,76.147000,333.596000,310.487000,187.665000,1132.181000,1392.868000,598.171000,59.564000,254.122000,32.020000

In [29]:

no_outliers

,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,AAWhiteSt-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,6.076,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
3,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,6.054,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
5,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,6.020,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.34
7,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,6.143,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.22
9,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,6.199,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,19.90,11.333,87.405,1171.206,369.383,343.515,310.115,1.592,452.718,6.296,...,55.963,330.842,308.789,128.701,783.417,1293.108,390.049,41.596,252.428,30.73
292,22.00,11.858,93.199,1171.206,366.787,345.261,310.115,1.513,428.202,6.340,...,52.494,330.589,309.152,137.719,816.020,1294.891,391.607,42.080,253.206,30.24
294,19.00,12.425,92.905,1272.030,316.226,345.811,313.147,1.633,469.045,6.330,...,60.307,329.997,308.072,137.719,865.661,1292.216,391.645,44.330,253.323,30.31
296,20.50,13.358,97.662,1304.597,377.678,347.672,313.147,1.546,496.460,6.340,...,60.119,332.615,308.575,141.076,997.904,1334.703,389.497,46.206,252.423,30.43
298,20.90,15.167,84.640,1283.706,339.440,354.803,311.041,1.635,532.419,6.340,...,65.561,332.924,307.626,145.299,832.906,1344.708,388.911,49.524,251.833,30.29